source 'http://ruby.taobao.org'

ruby '2.1.1'

gem 'yard'
gem 'thor'
gem 'msgpack'
gem 'logger'
gem 'sqlite3'
gem 'rake'
gem 'bundle'
gem 'celluloid'
gem 'celluloid-io'
gem 'activerecord'
gem 'rspec'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'guard-rspec'
gem 'growl'